server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
      - id: empresa_service
        uri: lb://empresa
        predicates:
        - Path=/api/empresa/**
        #filters:
        #- name: AuthenticationFiltering

      - id: evaluacion_service
        uri: lb://evaluacion
        predicates:
        - Path=/api/evaluacion/**

      - id: keycloak_service
        uri: lb://infraestructure-keycloak
        predicates:
        - Path=/api/security/**